Feature/data object
CPNV-ES-BI/BI_CSHARP_GCP pull request #4
Opened 2022-12-21 12:29 UTC by Penfu

@NicolasGlassey Vous pouvez review cette PR.

- Classe de test 'TestGCPDataObject' incomplète.
- Github actions

2023-01-13 10:56 UTC, MauroWasTaken approved these changes
the application side of this PR will be reviewed in seperate features

2023-01-13 13:32 UTC, NicolasGlassey commented on doc/sequences/publish.puml
> +App -> GCP: DoesExist Request
Is it really the responsibility of the Publish Method to test if the object does exist?

The SDK already returns an exception if the object wasn't found. Publish has to correctly deal with this exception, but for me, the client (the class that calls the publish method) is responsible of this.

2023-01-13 13:39 UTC, NicolasGlassey commented on doc/sequences/download.puml
> +App -> GCP: DoesExist Request
Same issue... the same question of responsibility. The client is responsible to use correctly the create method. Are any other exceptions you have to deal with?

2023-01-13 13:50 UTC, NicolasGlassey requested changes
@MauroWasTaken  @Penfu 

Please find as comments, some issues I had on several .puml files (sequences).

Globally, be careful of the concern of responsibility. The "DoesExist" method is already responsible to check if an object exists. All other methods are specialized for other purposes. This is the client who is responsible to use correctly the method (pre-conditions).

I propose you merge those singular sequence diagrams in a real scenario. The sequence must be more "integration test" oriented.

Publish a new object from its creation, with all possible cases. I request only one sequence, but with everything, we need for the DataObjectHelper.

2023-01-18 09:00 UTC, Penfu commented on doc/sequences/exist.puml
> +
@NicolasGlassey We didn't found an SDK-level method to check if an object exists. 

That's why we perform a get of the object to the SDK  and he return the object or an exception.
Base on this answer we return to the client the corresponding bolean statement. The SDK exception isn't thrown further.

2023-01-18 09:02 UTC, Penfu commented on doc/sequences/publish.puml
> +App -> GCP: DoesExist Request
Solve in this [commit](https://github.com/CPNV-ES-BI/BI_CSHARP_GCP/commit/6ca4b6d6232df5449d33513c6bcd197fac593079).

2023-01-18 09:14 UTC, Penfu commented on doc/sequences/download.puml
> +App -> GCP: DoesExist Request
Solve in this [commit](https://github.com/CPNV-ES-BI/BI_CSHARP_GCP/commit/5f67e667425ec220665b3b1d474be7c7bf44952b).

It is also possible to receive an exception from the SDK regarding the client's access rights to the object. But we will not handle this case in this sprint.

2023-01-19 20:20 UTC, Penfu commented
# Publish

## Issue

Google.GoogleApiException : 'The service storage has thrown an exception. HttpStatusCode is BadRequest. Cannot update access control for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access'

## Solution

To allow to attach specific access  right to an object change bucket policy with: `gsutil uniformbucketlevelaccess set off gs://[BUCKET_NAME]`

2023-01-19 20:34 UTC, Penfu commented
# Publish public access prevention is enforced

## Issue

Google.GoogleApiException : 'The service storage has thrown an exception. HttpStatusCode is PreconditionFailed. The member bindings allUsers and allAuthenticatedUsers are not allowed since public access prevention is enforced.'

## Solution

Go to Storage browser in the GCP Console, find your bucket, click on the three dots on the right, and select Edit bucket then click on Permissions tab and uncheck Block all public access.

Didn't find the CLI.

2023-01-20 12:08 UTC, Penfu commented
In order to implement the API, this PR is merge.

2023-01-20 12:09 UTC, merged